### ISSUE TITLE
Firefox autofills New Password field in user editing form.

### ISSUE THREAD

**Issue by jamestmartin** [LastArtistStanding/last-artist-standing#50]
The solution would probably be to add `autocomplete="new-password"` to `<input class="form-control " type="password" name="user[password]" id="user_password">` in [_editform.html.erb](https://github.com/LastArtistStanding/last-artist-standing/blob/master/app/views/users/_editform.html.erb), see https://bugzilla.mozilla.org/show_bug.cgi?id=1119063.

I would do this myself and send a PR, but it's not worth learning Ruby for a one-off change like this.

**Comment by the1banana** [comment]
Resolved with patch 1.1.3!
